export const SCORES = {
  CODE_QUALITY: {
    BASE: 40,
    TESTS: 15,
    CI: 15,
    LICENSE: 5,
    COMMIT: 5,
    VERY_ACTIVE_COMMIT: 5,
    CONTRIBUTORS: 5,
    STRONG_COLLABORATION: 5,
    LOW_ISSUE_COUNT: 5,
  },
  DOCUMENTATION: {
    BASE: 20,
    README: 45,
    ADDITIONAL_DOC: 20,
    MEANINGFUL_DESCRIPTION: 5,
    LICENSE_DOC: 10,
  },
  PROJECT_STRUCTURE: {
    BASE: 30,
    CONFIG: 15,
    SRC_DIR: 15,
    PACKAGE_MANAGER: 20,
    GITIGNORE: 10,
    MULTI_LANG: 10,
  },
};

export const WEIGHTS = {
  CODE_QUALITY: 0.4,
  DOCUMENTATION: 0.3,
  PROJECT_STRUCTURE: 0.3,
};
